New, perl version of condor_submit_dag.  Unless you specify "-log filename" on the command-line, this will go through the DAG input file you give, find all the submit files referenced, and make sure each one points to the same user log file.  So, the name of the logfile for all jobs is no longer hard coded.  Other improvements: more clear messages, checks for condor_dagman to be installed, etc, etc.

diff --git a/src/condor_dagman/condor_submit_dag b/src/condor_dagman/condor_submit_dag
--- a/src/condor_dagman/condor_submit_dag
+++ b/src/condor_dagman/condor_submit_dag
@@ -1,57 +1,250 @@
-#!/bin/csh -f
+#!/usr/bin/perl
 
-  set D = ""      # The DAG file
-  @ SUBMIT = 1    # Boolean, submit to condor
+###########################################################################
+#
+#  This is condor_submit_dag.  It takes a DAG input file to be used by
+#  condor_dagman, analyzes it for correctness and gleens important
+#  information.  Then, it creates a file used to submit condor_dagman
+#  to Condor as a "meta-scheduler" with this DAG file.  Finally,
+#  unless you specify the "-no_submit" option to condor_submit_dag, it
+#  actually submits this newly-created file to Condor, which spawns 
+#  the condor_dagman binary on your local machine (and will restart it
+#  if the local machine crashes, etc).  
+#
+#  Other than setting the proper path to perl above, you should not
+#  need to edit this script at all.
+#
+#  condor_submit_dag by Derek Wright <wright@cs.wisc.edu> 1/8/99
+#
+###########################################################################
 
-  switch ($#argv)
-    case 1:
-      set D = $argv[1]
-      breaksw
-    case 2:
-      if ($argv[1] == "-n") then
-        @ SUBMIT = 0
-      else
-        goto USAGE
-      endif
-      set D = $argv[2]
-      breaksw
-    default:
-      goto USAGE
-  endsw
+print "\n";
+# Parse command-line args
+$submit = 1;
+$force = 0;
+$notification = "";
+while( $_ = shift ) {
+  SWITCH: {	    
+    if( /^-no_s.*/ ) {
+	$submit = 0;
+	last SWITCH;
+    } 
+    if( /^-v.*/ ) {
+	$verbose = 1;
+	last SWITCH;
+    } 
+    if( /^-f.*/ ) {
+	$force = 1;
+	last SWITCH;
+    } 
+    if( /^-not.*/ ) {
+	$notification = shift;
+	if( ! grep(/$notification/i, ("always", "complete", "error", "never")) ) {
+	    print "Invalid argument to -notification option: $notification\n";
+	    &usage();
+	}
+	last SWITCH;
+    }
+    if( /^-l.*/ ) {
+	$job_log = shift;
+	if( ! $job_log ) {
+	    &usage();
+	}
+	last SWITCH;
+    }
+    $dagfile = $_;
+  }
+}
+if( ! $dagfile ) {
+    &usage();
+} else {
+    # Setup some filenames we're going to want to use.
+    $lib_log = "$dagfile.lib.out";
+    $debug_log = "$dagfile.dagman.out";
+    $sched_log = "$dagfile.dagman.log";
+    $sub_file = "$dagfile.condor.sub";
+}
 
-  set DC = $D.condor
+# Figure out if condor_dagman is installed, and if so, where. 
+chop( $dagman_path = `which condor_dagman` );
+-x $dagman_path || 
+    die "Can't find the condor_dagman exectuable in your PATH, aborting.\n";
 
-  echo "# Filename: $DC"                       > $DC
-  echo "# Generated by condor_submit_dag $D"  >> $DC
-  echo "executable   = `which condor_dagman`" >> $DC
-  echo "output       = $D.stdout"             >> $DC
-  echo "error        = $D.stderr"             >> $DC
-  echo "log          = $D.log"                >> $DC
-  echo "arguments    = -f -t -l . -Debug 3 -Lockfile $D.lock -Condorlog $D.condor.log -Dag $D" >> $DC
-  echo "environment  = PATH=$PATH"            >> $DC
-  echo "universe     = scheduler"             >> $DC
-  echo "notification = ALWAYS"                >> $DC
-  echo "queue"                                >> $DC
+# Make sure all the files we're going to use are available, and if
+# not, exit with an error message.  If we were given "-force", don't
+# print the error and exit, just remove them.
+&check_output_files();
+
+# Figure out what the log file should be called.  If there are
+# multiple log files mentioned, this function will abort.  If we were
+# told on the command-line, we just use that, and print a warning
+# message.  If we were told not to check the whole thing, we just read
+# the first one out and use that. 
+if( $job_log ) {
+    print "Using \"$job_log\" as the log file shared by all jobs in this DAG.\n";
+    print "Please be sure you know what you're doing and that all jobs use this file.\n";
+} else {
+    print "Checking your DAG input file and all submit files it references.\n";
+    print "This might take a while... \n";
+    $job_log = &parse_dag_file();
+    print "Done.\n";
+}
+
+# Create the submit file used to submit DAGMan as a scheduler universe
+# job to Condor. 
+&write_submit_file();
+
+# Print closing remarks, and actually submit the DAG if that's wanted.
+print "-----------------------------------------------------------------------\n";
+print "File for submitting this DAG to Condor   : $sub_file\n";
+print "Log of DAGMan debugging messages         : $debug_log\n";
+print "Log of Condor library debug messages     : $lib_log\n";
+print "Log of the life of condor_dagman itself  : $sched_log\n";
+print "\n";
+print "Condor Log file for all jobs of this DAG : $job_log\n";
+
+if( $submit ) {
+    print `condor_submit $sub_file`;
+} else {
+    print "-no_submit given, not submitting DAG to Condor.  You can do this with:\n";
+    print "\"condor_submit $sub_file\"\n";
+}
+print "-----------------------------------------------------------------------\n";
+exit( 0 );
 
 
-  echo "--------------------------------------------------------"
-  echo "CondorConfigFile for DAG written to: $DC"
-  echo "DAG's stdout             written to: $D.stdout"
-  echo "DAG's stderr             written to: $D.stderr"
-  echo "DAG's log file           written to: $D.log"
-  echo ""
-  echo "Condor Log file for all jobs of this DAG: $D.condor.log"
-  if ($SUBMIT) then
-    condor_submit $DC
-  else
-    echo "-n given, not submitting DAG to Condor"
-  endif
-  echo "--------------------------------------------------------"
-exit
+#################################################################
+## Subroutines
+#################################################################
 
-USAGE:
-  echo ""
-  echo "Usage: condor_submit_dag  NAME.dag"
-  echo "       where NAME is the name your DAG."
-  echo ""
-exit
+sub usage {
+    print "Usage: condor_submit_dag [options] filename\n";
+    print "  where filename is the name of your DAG input file\n";
+    print "  and where [options] is one or more of:\n";
+    print "    -no_submit          (DAG is not submitted to Condor)\n";
+    print "    -verbose            (Verbose error messages from condor_submit_dag)\n";
+    print "    -force              (Overwrite files condor_submit_dag uses if they exist)\n";
+    print "    -log filename       (Specify the log file shared by all jobs in the DAG)\n";
+    print "    -notification value (Determines how much email you get from Condor\n";
+    print "         about the life of the condor_dagman job.  'value' must be\n";
+    print "         one of \"always\", \"never\", \"error\", or \"complete\".\n";
+    print "         See the condor_submit man page for details.)\n";
+    exit( 1 );
+}
+
+sub parse_dag_file {
+    local( %cmd_files, %log_names, $log_name, $had_error, $len, $max );
+    $had_error = 0;
+    open( DAG, "<$dagfile" ) || die "Can't open $dagfile for reading: $!\n";
+    while( <DAG> ) {
+	if( /^job\s*(\S*)\s*(\S*)$/i ) {
+	    $cmd_files{$2} = 1;
+	}
+    }
+    close DAG;
+    foreach $file (sort keys %cmd_files ) {
+	if( ! open( FOO, "<$file" ) ) {
+	    print "\nCan't open command file $file for reading: $!\n";
+	    print "Either create $file or re-run with the \"-log\" option.\n";
+	    if( ! $verbose ) {
+		print "Use the \"-verbose\" option for a more verbose error message.\n";
+		exit( 1 );
+	    }	    
+	    print "If all the command files in your DAG don't exist now, consider running\n";
+	    print "condor_submit_dag with the \"-log filename\" option to specify the log file\n";
+	    print "shared by all jobs in your DAG.  This avoids this check.\n";
+	    print "If you do so, you must be sure those files are created when they are needed,\n";
+	    print "probably by using the PRE and POST directives in your DAG file.\n";
+	    print "See the DAGMan manual for more details.\n";
+	    exit( 1 );
+	}
+	while( <FOO> ) {
+	    if( /^log\s*=\s*(.*)/i ) {
+		$log_names{$file} = $1;
+		if( ! $log_name ) { $log_name = $1; }
+	    }
+	}
+	close FOO;
+    }
+    foreach $file (sort keys %log_names ) {
+	$len = length $file;
+	if( $log_names{$file} ne $log_name ) {
+	    print "ERROR: log file specified in $file is not \"$log_name\".\n";
+	    $had_error = 1;
+	}
+    }
+    if( $had_error ) {
+	print "\nAll jobs submitted in this DAG must share the same log file.  ";
+	print "Please look\nat all the submit files and make sure they each specify ";
+	print "the same filename\nin their \"log = filename\" settings.\n\n";
+	if( $verbose ) {
+	    print "The submit files your DAG file mentions and the log file each uses are:\n";
+	    foreach $file (sort keys %cmd_files ) {
+		printf( "   %-20s%s\n", $file, $log_names{$file} );
+	    }
+	} else {
+	    print "To see all the log files you mention in each submit file you use, ";
+	    print "run\ncondor_submit_dag again with the -verbose option.\n";
+	}
+	exit( 1 );
+    }
+    return $log_name;
+}
+
+
+sub write_submit_file {
+    local( $path ) = $ENV{PATH};
+
+    open( SUBMIT, ">$sub_file" ) 
+	|| die "Can't open $sub_file for writing: $!\n";
+
+    print SUBMIT "# Filename: $sub_file\n";
+    print SUBMIT "# Generated by condor_submit_dag $dagfile\n";
+    print SUBMIT "universe\t= scheduler\n";
+    print SUBMIT "executable\t= $dagman_path\n";
+    print SUBMIT "output\t\t= $debug_log\n";
+    print SUBMIT "error\t\t= $lib_log\n";
+    print SUBMIT "log\t\t= $sched_log\n";
+    print SUBMIT "arguments\t= -f -t -l . -Debug 3 -Lockfile $dagfile.lock -Condorlog $job_log -Dag $dagfile\n";
+    print SUBMIT "environment\t= PATH=$path\n";
+    if( $notification ) {
+	print SUBMIT "notification\t= $notification\n";
+    }
+    print SUBMIT "queue\n";
+
+    close SUBMIT;
+}
+
+
+sub check_output_files() {
+    local( $had_error ) = 0;
+    if( $force ) {
+	unlink( "$sub_file" );
+	unlink( "$debug_log" );
+	unlink( "$sched_log" );
+	unlink( "$lib_log" );
+    } else { 
+	if( -f $sub_file ) {
+	    $had_error = 1; 
+	    print "ERROR: \"$sub_file\" already exists.\n";
+	}
+	if( -f $lib_log ) {
+	    $had_error = 1; 
+	    print "ERROR: \"$lib_log\" already exists.\n";
+	}
+	if( -f $debug_log ) {
+	    $had_error = 1; 
+	    print "ERROR: \"$debug_log\" already exists.\n";
+	}
+	if( -f $sched_log ) {
+	    $had_error = 1; 
+	    print "ERROR: \"$sched_log\" already exists.\n";
+	}
+	if( $had_error ) {
+	    print "Some file(s) needed by condor_submit_dag already exist.  ";
+	    print "Either rename them,\nor use the \"-f\" option to force them ";
+	    print "to be overwritten.\n";
+	    exit( 1 );
+	}
+    }
+}
