Fixed silly sleep 5 in init stop
It was replaced with a call to wait_pid, which waits up to 15 seconds
for the condor_master to exit. An existing issue is if the master
still hasn't exited after those 15 seconds and stop was invoked as
part of restart (or if start is invoked before the condor_master
exists, generally) the subsequent start will think that the master is
already running, which it is, and will not do anything. The result is
the master will eventually exit and not actually be restart.

diff --git a/src/condor_examples/condor.init b/src/condor_examples/condor.init
--- a/src/condor_examples/condor.init
+++ b/src/condor_examples/condor.init
@@ -50,7 +50,13 @@ stop() {
     killproc -p $pidfile $prog -QUIT
     RETVAL=$?
     echo
-    sleep 5
+    wait_pid $pidfile 15
+    if [ $? -ne 0 ]; then
+	# If this happens during a restart the start is likely to see
+	# condor still running and just return 0, which means when
+	# condor exits it won't be restarted
+	echo $"Warning: $prog may not have exited, start/restart may fail"
+    fi
     [ $RETVAL -eq 0 ] && rm -f $lockfile
     return $RETVAL
 }
@@ -85,26 +91,73 @@ reload() {
 #         4 = status unknown
 #
 pid_status() {
-    if [ -f $1 ]; then
-        # this can fail if we're not privileged
-        pid=`cat $1` &>/dev/null
-        if [ $? -ne 0 -o -z "$pid" ]; then
-            return 4
-        fi
+    pid=$(get_pid $1)
+    case $? in
+	1) return 3 ;;
+	2) return 4 ;;
+    esac
 
-        ps $pid &>/dev/null
-        if [ $? -ne 0 ]; then
-	    if [ -e $2 ]; then
-		return 2
-	    fi
+    ps $pid &>/dev/null
+    if [ $? -ne 0 ]; then
+	if [ -e $2 ]; then
+	    return 2
+	fi
 
-            return 1
-        fi
-
-        return 0
+	return 1
     fi
 
-    return 3
+    return 0
+}
+
+#
+# Wait for the pid in the pidfile to disappear, but only do so for at
+# most timeout seconds.
+#
+# Usage: wait_pid <pidfile> <timeout>
+# Result: 0 = pid was not found (doesn't exist or not accessible)
+#         1 = pid still exists after timeout
+wait_pid() {
+    pid=$(get_pid $1)
+    if [ $? -ne 0 ]; then
+	return 0
+    fi
+
+    wait=0
+    while [ $wait -lt $2 ]; do
+	pid_status $1 /dev/null   # ingore lockfile
+	if [ $? -ne 0 ]; then
+	    return 0
+        fi
+	ps $pid
+
+	sleep 1
+	wait=$((wait + 1))
+    done
+
+    return 1
+}
+
+#
+# Retrieve pid from a pidfile
+#
+# Usage: get_pid <pidfile>
+# Result: 0 = pid returned
+#         1 = pidfile not found
+#         2 = pidfile not accessible or didn't contain pid
+# Stdout: pid
+#
+get_pid() {
+    if [ -f $1 ]; then
+	pid=`cat $1` &>/dev/null
+	if [ $? -ne 0 -o -z "$pid" ]; then
+	    return 2
+	fi
+
+	echo -n $pid
+	return 0
+    fi
+
+    return 1
 }
 
 
