Add support for rvgahp in remote gahp scripts. HTCONDOR-1007
remote_gahp now has options to use rvgahp_client. condor_remote_cluster
now includes rvgahp_server in the files it installs on the cluster head
node.

diff --git a/src/condor_gridmanager/remote_gahp b/src/condor_gridmanager/remote_gahp
--- a/src/condor_gridmanager/remote_gahp
+++ b/src/condor_gridmanager/remote_gahp
@@ -34,7 +34,8 @@ PRIVATE_KEY_LOCATION=`echo ~/.ssh/bosco_key.rsa`
 # Set 'ssh -o BatchMode yes' by default so we fail if a password is requested
 SSH_BATCHMODE=yes
 BASH_LOGIN=yes
-
+RVGAHP=no
+RVGAHP_SOCKET=""
 
 # Parse command line arguments 
 PROG_NAME=$0
@@ -81,6 +82,9 @@ while [ $# != 0 ] ; do
         --rgahp-* ) echo "Unknown option: $1" 1>&2
             echo -e "$USAGE"
             exit 1;;
+        --rvgahp-socket ) RVGAHP_SOCKET="$2"
+            RVGAHP=yes
+            shift 2;;
         -- ) shift
             if [ "$REMOTE_CMD" = "" -o "$1" = "condor_ft-gahp" ] ; then
                 REMOTE_CMD="$1"
@@ -114,6 +118,13 @@ fi
 if [ "$REMOTE_CMD" = "" ] ; then
     echo "Missing remote command" 1>&2
     echo -e "$USAGE"
+    exit 1
+fi
+
+if [ "$RVGAHP" = "yes" ] ; then
+    # TODO handle default RVGAHP_SOCKET
+    exec $(condor_config_val SBIN)/rvgahp_client "${RVGAHP_SOCKET}" "${REMOTE_CMD}"
+    echo "Failed to run rvgahp_client" 1>&2
     exit 1
 fi
 
