Add check for conflicting collector port to bosco_quickstart.
If Bosco's default collector port of 11000 is in use, find another one.

From OSG Jira CAMPUS-105

diff --git a/src/condor_contrib/bosco/bosco_quickstart b/src/condor_contrib/bosco/bosco_quickstart
--- a/src/condor_contrib/bosco/bosco_quickstart
+++ b/src/condor_contrib/bosco/bosco_quickstart
@@ -17,6 +17,7 @@ LOG_FILE=./bosco_quickstart.log
 # which
 # python
 # wget or curl if download needed
+# netstat to check for a free port
 
 display_dots () {
     if [ "x$1" != "x" ]; then
@@ -59,6 +60,41 @@ show_progress () {
     
     return $exit_code
 
+}
+
+fix_port () {
+  # Checks if the port is available
+  # If the port is already used it sweeps until a port is available
+  which netstat &> /dev/null
+  if [ $? -ne 0 ]; then
+    echo "No netstat available, unable to verify if port $1 is free" >> $LOG_FILE
+    return 1
+  fi
+  let start_port=$1
+  let tmp_max=$start_port+2000
+  let tmp_port=$start_port
+  while [ $tmp_port -le $tmp_max ]; do
+    netstat -tulpn 2> /dev/null | grep $tmp_port > /dev/null 2>&1
+    [ $? -eq 1 ]  && break
+    let tmp_port=$tmp_port+1
+  done
+  if [ $tmp_port -eq $start_port ]; then
+    # Initil port is available
+    return 0
+  fi
+  if [ $tmp_port -le $tmp_max ]; then
+    # Found a free port in the range
+    factory_config=$HOME/bosco/local.bosco/config/condor_config.factory
+    echo "Port $start_port is busy. Replacing port $start_port with $tmp_port. Before:" >> $LOG_FILE
+    grep $start_port $factory_config >> $LOG_FILE
+    sed "s;$start_port;$tmp_port;" < $factory_config > ${factory_config}.new
+    mv ${factory_config}.new ${factory_config}
+    echo "After replacement:" >> $LOG_FILE
+    grep $tmp_port $factory_config >> $LOG_FILE
+    return 0
+  fi
+  echo "No free port in range $start_port to $tmp_port" >> $LOG_FILE
+  return 1
 }
 
 
@@ -118,6 +154,8 @@ if [ $? -ne 0 ]; then
   source $HOME/bosco/bosco_setenv
 fi
 
+# Check if port 11000 (BOSCO default) is available
+fix_port 11000
 
 # Start Bosco
 echo "************** Starting Bosco: ***********"
