This is the 1.0rc2 commit for the ClassAd Library. Through extensive work with Alain Roy (including code review), this commit contains a new way of building the ClassAd library through autoconf/automake, builds static and shared libraries using libtool, and has numerous other enhancements, including some bug fixes and memory leaks. For an extensive list check the CHANGELOG. The Italian Francescos (EGEE) have also be consulted on the changes as they are major users of the ClassAd library.

diff --git a/src/condor_classad.V6/build_external b/src/condor_classad.V6/build_external
--- a/src/condor_classad.V6/build_external
+++ b/src/condor_classad.V6/build_external
@@ -7,7 +7,7 @@
 cd $PACKAGE_BUILD_DIR/$PACKAGE_NAME/
 
 ##### Configure and Build ClassAds #####
-./configure --enable-namespace --prefix $PACKAGE_INSTALL_DIR
+./configure --enable-namespace --prefix=$PACKAGE_INSTALL_DIR CC=g++
 if [ $? -ne 0 ]
 then
     echo "Configure failed"
@@ -22,19 +22,25 @@ then
 fi
 
 ##### Test the ClassAd build #####
-./classad_unit_tester
+#./classad_unit_tester
+#if [ $? -ne 0 ]
+#then
+#    echo "Unit tests failed"
+#    exit 2
+#fi
+#
+#./classad_functional_tester functional_tests.txt
+#if [ $? -ne 0 ]
+#then
+#    echo "Functional tests failed"
+#    exit 2
+#fi
+make check
 if [ $? -ne 0 ]
 then
-    echo "Unit tests failed"
+    echo "make check"
     exit 2
-fi
 
-./classad_functional_tester functional_tests.txt
-if [ $? -ne 0 ]
-then
-    echo "Functional tests failed"
-    exit 2
-fi
 
 ##### Install the ClassAd build #####
 make install
