More robust maintainer scripts.
Handle daemon start/stop manually, with more sanity checks.

diff --git a/debian/condor.prerm b/debian/condor.prerm
--- a/debian/condor.prerm
+++ b/debian/condor.prerm
@@ -9,17 +9,34 @@ condor_remove_homedir() {
 		# should we rely on the configuration to be sane?
 		#rm -rf $dname
 		# better have some safety-net and only delete what belongs to condor
-		find $dname -type f -user condor -group condor -delete
+		# if we have a condor user at all
+		id -u condor > /dev/null 2>&1 && find $dname -type f -user condor -group condor -delete
 		# try getting rid of the directory as well, but do not fail if there
 		# were left-overs
 		rmdir $dname || true
 	done
 }
 
-# dh_installdeb will replace this with shell code automatically
-# generated by other debhelper scripts.
-
-#DEBHELPER#
+# handle stopping condor seperately to prevent jobs from being killed
+# without reason, but we cannot avoid stopping condor during removal
+# or upgrade -- in the former it is desired and in the latter case condor
+# would also do it by itself
+case "$1" in
+	upgrade|remove)
+		# init script fails of RUN is not there (i.e. broken install)
+		if [ -x "/etc/init.d/condor" -a -d $(condor_config_val RUN) ]; then
+			if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
+			invoke-rc.d condor stop || exit $?
+		else
+			/etc/init.d/condor stop || exit $?
+			fi
+		fi
+	;;
+	*)
+		echo "prerm called with unknown argument \`$1'" >&2
+		exit 1
+	;;
+esac
 
 case "$1" in
 	remove)
@@ -39,5 +56,10 @@ case "$1" in
 		exit 1
 	;;
 esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+#DEBHELPER#
 
 exit 0
