Check the status of ssh-copy-id in bosco_cluster --add
The ssh-copy-id will fail if the user cannot log into
the remote machine.  We need to catch the error in order to
not copy files over to the failing machine.

diff --git a/src/condor_scripts/bosco_cluster b/src/condor_scripts/bosco_cluster
--- a/src/condor_scripts/bosco_cluster
+++ b/src/condor_scripts/bosco_cluster
@@ -295,6 +295,10 @@ fi
 # ssh-copy-id is available on el5 from openssh-clients
 echo "Enter password to copy ssh keys to $remote_host:"
 ssh-copy-id -i $bosco_key $remote_host > /dev/null
+if [ $? -ne 0 ]; then
+    echo "Error running ssh-copy-id.  Please make sure you password is correct."
+    exit 1
+fi
 
 start_ssh
 
