HTCONDOR-2341: Take blessed RC tarball from update subdirectory
The OSPool will be using our blessed RCs from the update subdirectory
of the tarball area. condor_remote_cluster needs to know about the
update subdirectory for blessed RCs.

diff --git a/src/condor_scripts/condor_remote_cluster b/src/condor_scripts/condor_remote_cluster
--- a/src/condor_scripts/condor_remote_cluster
+++ b/src/condor_scripts/condor_remote_cluster
@@ -677,6 +677,7 @@ eval set -- "$TEMP"
 platform_force=
 override_dir=
 release_url=
+update_url=
 rc_url=
 daily_url=
 
@@ -846,6 +847,9 @@ if [ -z "${release_url}" ]; then
     if echo "${ver_str[*]}" | grep -q -e "PRE-RELEASE" -e " RC " -e "UW_development" ; then
         rc_url="${url_base}${series}/${version}/rc/condor-${version}-${platform}-stripped.tar.gz"
     fi
+    if echo "${ver_str[*]}" | grep -q -e "PRE-RELEASE" -e " RC " -e "UW_development" ; then
+        update_url="${url_base}${series}/${version}/update/condor-${version}-${platform}-stripped.tar.gz"
+    fi
 fi
 
 # Create a tmp dir, download the files and rsync them to the remote system
@@ -858,6 +862,14 @@ if [ ! -z "$daily_url" ] ; then
     rc=$?
     if [ $rc -ne 0 ] ; then
         echo "Failed to download daily build."
+    fi
+fi
+# Prefer blessed RC
+if [ ! -z "$update_url" -a $rc -ne 0 ] ; then
+    show_progress "Downloading update build for $remote_host" curl -f -s -S -o $tmp_dir/bosco-download.tar.gz $update_url
+    rc=$?
+    if [ $rc -ne 0 ] ; then
+        echo "Failed to download update build."
     fi
 fi
 if [ ! -z "$rc_url" -a $rc -ne 0 ] ; then
