+ Added code to chown to the username supplied by condor_config_val   -owner, instead of just chowning to condor (or not chowning at all!) + execute doesn't have to be world writable, (nor have the sticky-bit) + Added code to create the lock dir as specified in LOCK unless it's   equal to LOG (which we already created).

diff --git a/src/condor_scripts/condor_init b/src/condor_scripts/condor_init
--- a/src/condor_scripts/condor_init
+++ b/src/condor_scripts/condor_init
@@ -7,18 +7,27 @@
 
 HOSTNAME=`hostname`
 CONFIG_VAL="condor_config_val -h $HOSTNAME"
+OWNER=`condor_config_val -owner 2> /dev/null`
+if [ ! -n "$OWNER" ]; then
+   echo "Error determining who should own the Condor-related directories."
+   echo "Either create a "condor" account, or set the CONDOR_IDS environment"
+   echo "variable to the valid uid.gid pair that should be used by Condor."
+   exit 1
+fi
 
 CONDOR_LOCALDIR=`$CONFIG_VAL LOCAL_DIR 2> /dev/null`
 CONDOR_LOG=`$CONFIG_VAL LOG 2> /dev/null`
 CONDOR_SPOOL=`$CONFIG_VAL SPOOL 2> /dev/null`
 CONDOR_EXECUTE=`$CONFIG_VAL EXECUTE 2> /dev/null`
 CONDOR_LOCALCFG=`$CONFIG_VAL LOCAL_CONFIG_FILE 2> /dev/null`
+CONDOR_LOCK=`$CONFIG_VAL LOCK 2> /dev/null`
 
 if [ -n "$CONDOR_LOCALDIR" ]; then
 	if [ ! -d $CONDOR_LOCALDIR ]; then
 		echo "Creating $CONDOR_LOCALDIR"
 		mkdir $CONDOR_LOCALDIR
 		chmod 755 $CONDOR_LOCALDIR
+		chown $OWNER $CONDOR_LOCALDIR
 	fi
 else
 	echo "LOCAL_DIR is not defined, will not create"
@@ -33,6 +42,7 @@ if [ -n "$CONDOR_LOG" ]; then
 			exit 1
 		fi
 		chmod 755 $CONDOR_LOG
+		chown $OWNER $CONDOR_LOG
 	else
 		echo "$CONDOR_LOG already exists."
 	fi
@@ -55,6 +65,7 @@ if [ -n "$CONDOR_SPOOL" ]; then
 		echo "Creating $CONDOR_SPOOL"
 		mkdir $CONDOR_SPOOL
 		chmod 700 $CONDOR_SPOOL
+		chown $OWNER $CONDOR_EXECUTE
 	else
 		echo "$CONDOR_SPOOL already exists."
 	fi
@@ -75,7 +86,8 @@ if [ -n "$CONDOR_EXECUTE" ]; then
 	if [ ! -d $CONDOR_EXECUTE ]; then
 		echo "Creating $CONDOR_EXECUTE"
 		mkdir $CONDOR_EXECUTE
-		chmod 1777 $CONDOR_EXECUTE
+		chmod 755 $CONDOR_EXECUTE
+		chown $OWNER $CONDOR_EXECUTE
 	else
 		echo "$CONDOR_EXECUTE already exists."
 	fi
@@ -93,6 +105,18 @@ if [ -n "$CONDOR_LOCALCFG" ]; then
 	fi
 else
 	echo "LOCAL_CONFIG_FILE is not defined, will not create."
+fi
+
+if [ -n "$CONDOR_LOCK" ]; then
+	if [ ! -d $CONDOR_LOCK -a "$CONDOR_LOCK" != "$CONDOR_LOG" ];
+	then
+		echo "Creating $CONDOR_LOCK"
+		mkdir $CONDOR_LOCK
+		chmod 755 $CONDOR_LOCK
+		chown $OWNER $CONDOR_LOCK
+	fi
+else
+	echo "LOCK is not defined, will not create."
 fi
 
 echo "Condor has been initialized, but not started."
