HTCONDOR-2266: Add make-ap-from-tarball script

diff --git a/src/condor_scripts/make-personal-from-tarball b/src/condor_scripts/make-personal-from-tarball
--- a/src/condor_scripts/make-personal-from-tarball
+++ b/src/condor_scripts/make-personal-from-tarball
@@ -8,6 +8,18 @@ USER_ID=`id -u`
 GROUP_ID=`id -g`
 CONDOR_IDS=${USER_ID}.${GROUP_ID}
 
+PERSONAL=0
+AP=0
+BASENAME=$(basename $0)
+if [[ $BASENAME = 'make-personal-from-tarball' ]]; then
+    PERSONAL=1
+elif [[ $BASENAME = 'make-ap-from-tarball' ]]; then
+    AP=1
+else
+    echo "I don't know what condor setup you want"
+    exit 1
+fi
+
 if [[ $USER_ID -eq 0 || $GROUP_ID -eq 0 ]]; then
     echo "Please visit https://htcondor.readthedocs.io/en/latest/getting-htcondor for instructions on installing HTCondor as root."
     exit 1
@@ -30,6 +42,11 @@ fi
 
 if [[ -e ${LOCAL_CONFIG_DIR}/00-personal-condor ]]; then
     echo "Refusing to overwrite existing local/config.d/00-personal-condor file, aborting."
+    exit 1
+fi
+
+if [[ -e ${LOCAL_CONFIG_DIR}/00-ap-condor ]]; then
+    echo "Refusing to overwrite existing local/config.d/00-ap-condor file, aborting."
     exit 1
 fi
 
@@ -67,6 +84,12 @@ CONDOR_IDS=${CONDOR_IDS}
 EOF
 ) >> "${RELEASE_DIR}/etc/condor_config"
 
+if [[ $PERSONAL ]]; then
+    ROLE='use role: personal'
+elif [[ $AP ]]; then
+    ROLE='use role: submit'
+fi
+
 #
 # Because user-based authentication includes the hostname as part of the
 # identity, we have to set CONDOR_HOST back to the hostname for condor_off
@@ -75,7 +98,7 @@ EOF
 (
 cat <<EOF
 use security: user_based
-use role: personal
+${ROLE}
 CONDOR_HOST = \$(FULL_HOSTNAME)
 
 #
