HTCONDOR-3239: Normalize order of operations when making tarball

diff --git a/nmi_tools/glue/build/make-tarball-from-debs b/nmi_tools/glue/build/make-tarball-from-debs
--- a/nmi_tools/glue/build/make-tarball-from-debs
+++ b/nmi_tools/glue/build/make-tarball-from-debs
@@ -89,6 +89,12 @@ fi
 tar cfz condor_tests-$version-$release-$arch_dist.tar.gz condor_tests-$version-$release-$arch_dist
 rm -r condor_tests-$version-$release-$arch_dist
 
+$cmd_dir/make-tarball-links tarball
+if [ $? -ne 0 ];then
+    echo 'ERROR: tarball link script failed'
+    exit 1
+fi
+
 # Move configuration files back to example directory
 mv tarball/etc/condor/config.d/* tarball/usr/share/doc/condor/examples/
 
@@ -96,26 +102,21 @@ mv tarball/etc/condor/config.d/* tarball/usr/share/doc/condor/examples/
 for path in /usr/local/condor/externals/*.deb; do
     file=${path##*/}
     echo ======= $file =======
-    extract_deb $path tarball
     echo $file >> tarball/Manifest.txt
+    extract_deb $path tarball
 done
+
+$cmd_dir/set-tarball-rpath tarball '$ORIGIN/../lib:$ORIGIN/../lib/condor'
+if [ $? -ne 0 ];then
+    echo 'ERROR: set rpath script failed'
+    exit 1
+fi
 
 # Make necessary?? directories
 mkdir -p -m0700 tarball/etc/condor/passwords.d
 mkdir -p -m0700 tarball/etc/condor/tokens.d
 mkdir -p tarball/var/lib/condor/execute
 mkdir -p tarball/var/lib/condor/oauth_credentials
-
-$cmd_dir/make-tarball-links tarball
-if [ $? -ne 0 ];then
-    echo 'ERROR: tarball link script failed'
-    exit 1
-fi
-$cmd_dir/set-tarball-rpath tarball '$ORIGIN/../lib:$ORIGIN/../lib/condor'
-if [ $? -ne 0 ];then
-    echo 'ERROR: set rpath script failed'
-    exit 1
-fi
 
 # Add in apptainer if available
 if [ -d /usr/local/condor/externals/apptainer ]; then
