merged V6_5_0-branch into V6_5-branch, as tagged with V6_5_1 and since tagged at V6_5_0-merge-1.  this merge will break the build, but the fixes are small and IMHO not worth the hassle of a merge branch.

diff --git a/src/condor_globus/condor_glidein b/src/condor_globus/condor_glidein
--- a/src/condor_globus/condor_glidein
+++ b/src/condor_globus/condor_glidein
@@ -179,9 +179,12 @@ sub gather_info() {
 	$TMP = `$STATUS -master -format "%s" CondorVersion $CONDOR_HOST`;
 		#if we get a blank response because the collector isn't running
 		#a master in the same pool, try our master...
-	if ( !($TMP =~ /\S/) ) {
+	if ( $? != 0 || !($TMP =~ /\S/) ) {
 			$HOST = $ENV{'HOST'};
 			$TMP = `$STATUS -master -format "%s" CondorVersion $HOST`;
+			if ( $? != 0 ) {
+				$TMP = "";
+			}
 	}
 	( $_, $CONDOR_VERSION, $_) = split( / *[$: ]+/, $TMP );
 	if ( $CONDOR_VERSION eq "" ) {
@@ -224,7 +227,7 @@ sub gather_info() {
 	if ( silently( "$G_INFO -exists" ) ) {
 		return( "$NAME needs a valid grid proxy. (Re)run grid-proxy-init." );
 	}
-	if ( silently( "$G_INFO -hours 4" ) ) {
+	if ( silently( "$G_INFO -exists -hours 4" ) ) {
 		return( "Your grid proxy expires in less than four hours.\n"
 			. "Rerun grid-proxy-init." );
 	}
@@ -365,6 +368,8 @@ sub silently {
 		#child
 		close STDOUT;
 		close STDERR;
+		open( STDOUT, ">/dev/null" );
+		open( STDERR, ">/dev/null" );
 		exec( @_ );
 	}
 	return $?;
@@ -568,7 +573,7 @@ sub do_remote_setup() {
 			then \$GLOBUS_SH_MKDIR \$newdir;
 		fi
 		if [ ! -d \$newdir ];
-			then \$GLOBUS_SH_ECHO "ERROR mkdir \$newdir"
+			then echo "ERROR mkdir \$newdir"
 			exit 1;
 		fi
 	done
@@ -587,7 +592,7 @@ sub do_remote_setup() {
 	if [ \$GETFILES -eq 1 ]; then
 		\$GLOBUS_LOCATION/bin/globus-url-copy \$TARBALL_SERVER/\$ARCH.tar.gz file:\$ARCHDIR/\$ARCH.tar.gz;
 		if [ \$? != 0 -o ! -f \$ARCHDIR/\$ARCH.tar.gz ]; then
-			\$GLOBUS_SH_ECHO "Error: unable to retrieve \$TARBALL_SERVER/\$ARCH.tar.gz"
+			echo "Error: unable to retrieve \$TARBALL_SERVER/\$ARCH.tar.gz"
 			exit 1;
 		fi
 
