ssh_to_job now works with glexec.
    ===GT:Fixed=== #2263
    ===VersionHistory=== condor_ssh_to_job now works with jobs that
    are run via glexec.  Previously, it did not.

diff --git a/src/condor_starter.V6.1/condor_ssh_to_job_sshd_setup b/src/condor_starter.V6.1/condor_ssh_to_job_sshd_setup
--- a/src/condor_starter.V6.1/condor_ssh_to_job_sshd_setup
+++ b/src/condor_starter.V6.1/condor_ssh_to_job_sshd_setup
@@ -66,8 +66,14 @@ sshd_config="${sshd_dir}/sshd_config"
       s|_INSERT_FORCE_COMMAND_|${force_command}|g"\
  || die "Failed to create ${sshd_config}"
 
+sshd_user=`/usr/bin/whoami` || die "Failed to run /usr/bin/whoami"
+
 # now transmit stuff back to our caller on stdout
 # the caller expects specific markers before and after each item
+
+echo "condor_ssh_to_job_sshd_setup SSHD USER BEGIN"
+echo "${sshd_user}"
+echo "condor_ssh_to_job_sshd_setup SSHD USER END"
 
 echo "condor_ssh_to_job_sshd_setup SSHD DIR BEGIN"
 echo "${sshd_dir}"
