Porting glue changes to V7_6-branch so that it builds in new Batlab. There were some small changes to the configuration and CMake files as well.

diff --git a/nmi_tools/glue/test/remote_declare b/nmi_tools/glue/test/remote_declare
--- a/nmi_tools/glue/test/remote_declare
+++ b/nmi_tools/glue/test/remote_declare
@@ -1,7 +1,7 @@
-#!/bin/sh
+#!/usr/bin/env perl
 ##**************************************************************
 ##
-## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
+## Copyright (C) 1990-2011, Condor Team, Computer Sciences Department,
 ## University of Wisconsin-Madison, WI.
 ## 
 ## Licensed under the Apache License, Version 2.0 (the "License"); you
@@ -18,22 +18,227 @@
 ##
 ##**************************************************************
 
+use strict;
+use warnings;
+use Getopt::Long;
+use vars qw/ @opt_testclasses /;
+use File::Basename;
+use File::Spec;
 
-# $Id: remote_declare,v 1.3 2007-11-08 22:53:46 nleroy Exp $
+my $dir = dirname($0);
+unshift @INC, $dir;
+require "TestGlue.pm";
+TestGlue::print_debug_header();
+TestGlue::setup_test_environment();
 
-# Condor implementation of NMI test infrastructure interface
-# Simple wrapper to source the environment file and spawn the
-# corresponding perl script for a given stage of the test.
+parseOptions();
 
-ENV_FILE=setup_test_env
+######################################################################
+# generate list of all tests to run
+######################################################################
 
-# include the environment info from the pre-script
-if [ ! -f $ENV_FILE ]; then
-    echo "$ENV_FILE does not exist!"
-    exit 1
-fi
-. $ENV_FILE
+my $BaseDir = $ENV{BASE_DIR} || die "BASE_DIR not in environment!\n";
+my $TaskFile = File::Spec->catfile($BaseDir, "tasklist.nmi");
+my $UserdirTaskFile = File::Spec->catfile($BaseDir, "..", "tasklist.nmi");
+my $testdir = "condor_tests";
 
-exec remote_declare.pl $*
+# Look for a specific file that contains overrides for the default timeouts for some tests
+my %CustomTimeouts = load_custom_timeout_file();
+my %RuncountChanges = load_custom_runcount_file();
+
+# file which contains the list of tests to run on Windows
+my $WinTestList = File::Spec->catfile($BaseDir, $testdir, "Windows_list");
+my $ShortWinTestList = File::Spec->catfile($BaseDir, $testdir, "Windows_shortlist");
+
+# Figure out what testclasses we should declare based on our
+# command-line arguments.  If none are given, we declare the testclass
+# "all", which is *all* the tests in the test suite.
+my @classlist = @opt_testclasses;
+if( ! @classlist ) {
+    push( @classlist, "all" );
+}
+
+# The rest of argv, after the -- are any additional configure arguments.
+my $configure_args = join(' ', @ARGV);
+
+print "****************************************************\n";
+print "**** Preparing to declare tests for these classes:\n";
+foreach my $class (@classlist) {
+    print "****   $class\n";
+}
+
+# Make sure we can write to the tasklist file, and have the filehandle
+# open for use throughout the rest of the script.
+open(TASKFILE, '>', $TaskFile ) || die "Can't open $TaskFile for writing: $!\n"; 
+open(USERTASKFILE, '>', $UserdirTaskFile ) || die "Can't open $UserdirTaskFile for writing: $!\n"; 
 
 
+######################################################################
+# For each testclass, generate the list of tests that match it
+######################################################################
+
+my %tasklist;
+
+if( not TestGlue::is_windows() ) {
+    foreach my $class (@classlist) {
+    	print "****************************************************\n";
+    	print "**** Finding tests for class: '$class'\n";
+    	print "****************************************************\n";
+    	my $tests = findTests( $class, "top" );
+        %tasklist = (%tasklist, %$tests);
+    }
+}
+else {
+    # eat the file Windows_list into tasklist hash
+    foreach my $class (@classlist) {
+    	print "****************************************************\n";
+    	print "**** Finding Windows tests '$class'\n";
+    	print "****************************************************\n";
+        if($class eq "quick") {
+            open(WINDOWSTESTS, '<', $WinTestList) || die "Can't open $WinTestList: $!\n";
+        }
+        elsif($class eq "short") {
+            open( WINDOWSTESTS, '<', $ShortWinTestList) || die "Can't open $ShortWinTestList: $!\n";
+        }
+        else {
+            # if things got confused just run the hourly tests
+            print "Unknown test class provided for Windows: '$class' (only quick and short are supported)\n";
+            print "We will run the short tests in this undefined case.\n";
+            open( WINDOWSTESTS, '<', $ShortWinTestList) || die "Can't open $ShortWinTestList: $!\n";
+        }
+
+        # Load the tasks, one per line.  Skip comments (lines starting with #)
+        %tasklist = map { chomp; $_ => 1} grep !/^\s*\#/, <WINDOWSTESTS>;
+        print join("\n", sort keys %tasklist) . "\n";
+        close(WINDOWSTESTS);
+    }
+}
+
+my $total_tests = scalar(keys %tasklist);
+print "-- Found $total_tests test(s) in all directories\n";
+
+print "****************************************************\n";
+print "**** Writing out tests to tasklist.nmi\n";
+print "****************************************************\n";
+foreach my $task (sort keys %tasklist) {
+    my $test_count = defined($RuncountChanges{$task}) ? $RuncountChanges{$task} : 1;
+
+    if(defined($CustomTimeouts{"$task"})) {
+        print "CustomTimeout:$task $CustomTimeouts{$task}\n";
+        foreach(1..$test_count) {
+            print TASKFILE "$task-$_ $CustomTimeouts{$task}\n";
+            print USERTASKFILE "$task-$_ $CustomTimeouts{$task}\n";
+        }
+    }
+    else {
+        foreach(1..$test_count) {
+            print TASKFILE "$task-$_\n";
+            print USERTASKFILE "$task-$_\n";
+        }
+    }
+}
+close( TASKFILE );
+close( USERTASKFILE );
+print "Wrote " . scalar(keys %tasklist) . " unique tests.\n";
+exit(0);
+
+sub findTests {
+    my( $classname, $dir_arg ) = @_;
+    my ($ext, $dir);
+
+    if( $dir_arg eq "top" ) {
+        $ext = "";
+        $dir = $testdir;
+    }
+    else {
+        $ext = ".$dir_arg";
+        $dir = "$testdir/$dir_arg";
+    }
+    print "-- Searching directory '$dir' for tests with class '$classname'\n";
+    chdir( "$BaseDir/$dir" ) || die "Can't chdir($BaseDir/$dir): $!\n";
+
+    my $list_target = "list_$classname";
+    open(LIST, '<', $list_target) || die "cannot open $list_target: $!\n";
+    my %tasklist = map { chomp; "$_$ext" => 1 } <LIST>;
+    close(LIST);
+
+    print join("\n", sort keys %tasklist) . "\n";
+
+    my $total = scalar(keys %tasklist);
+    print "-- Found $total test(s) in directory '$dir' for class '$classname'\n\n";
+    return \%tasklist;
+}
+
+sub usage {
+    print <<EOF;
+--help          This help.
+--test-class    Which test class to run, comma separated or multiple occurrence.
+EOF
+	
+    exit 1;
+}
+
+# We use -- to delineate the boundary between args to this script and args to
+# the configure in this script.
+sub parseOptions {
+    print "Script called with ARGV: " . join(' ', @ARGV) . "\n";
+
+    my $rc = GetOptions('test-class=s' => \@opt_testclasses,
+                        'help'         => \&usage,
+                        );
+
+    if( !$rc ) {
+        usage();
+    }
+
+    # allow comma separated list in addition to multiple occurrences.
+    @opt_testclasses = split(/,/, join(',', @opt_testclasses));
+
+    if (!defined(@opt_testclasses)) {
+        die "Please supply a test class!\n";
+    }
+}
+
+
+sub load_custom_timeout_file {
+    my %timeouts = ();
+    my $TimeoutFile = File::Spec->catfile($BaseDir, $testdir, "TimeoutChanges");
+    if( -f $TimeoutFile) {
+        print "Found a custom timeout file at '$TimeoutFile'.  Loading it...\n";
+        open(TIMEOUTS, '<', $TimeoutFile) || die "Failed to open $TimeoutFile for reading: $!\n";
+        while(<TIMEOUTS>) {
+            if(/^\s*([\-\w]*)\s+(\d*)\s*$/) {
+                print "\tCustom Timeout: $1:$2\n";
+                $timeouts{$1} = $2;
+            }
+        }
+        close(TIMEOUTS);
+    }
+    else {
+        print "INFO: No custom timeout file found.\n";
+    }
+
+    return %timeouts;
+}
+
+
+sub load_custom_runcount_file {
+    my %runcounts = ();
+    my $RuncountFile = File::Spec->catfile($BaseDir, $testdir, "RuncountChanges");
+    if( -f $RuncountFile) {
+        print "Found a custom runcount file at '$RuncountFile'.  Loading it...\n";
+        open(RUNCOUNT, '<', $RuncountFile) || die "Failed to open $RuncountFile for reading: $!\n";
+        while(<RUNCOUNT>) {
+            if(/^\s*([\w\-]+)\s+(\d*)\s*$/) {
+                print "\tCustom Runcount: $1:$2\n";
+                $runcounts{$1} = $2;
+            }
+        }
+        close(RUNCOUNT);
+    }
+    else {
+        print "INFO: No custom runcount file found.\n";
+    }
+
+    return %runcounts;
+}
diff --git a/nmi_tools/glue/test/remote_post b/nmi_tools/glue/test/remote_post
--- a/nmi_tools/glue/test/remote_post
+++ b/nmi_tools/glue/test/remote_post
@@ -1,7 +1,7 @@
-#!/bin/sh
+#!/usr/bin/env perl
 ##**************************************************************
 ##
-## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
+## Copyright (C) 1990-2011, Condor Team, Computer Sciences Department,
 ## University of Wisconsin-Madison, WI.
 ## 
 ## Licensed under the Apache License, Version 2.0 (the "License"); you
@@ -19,19 +19,95 @@
 ##**************************************************************
 
 
-# $Id: remote_post,v 1.3 2007-11-08 22:53:46 nleroy Exp $
+######################################################################
+# post script for Condor testsuite runs
+######################################################################
 
-# Condor implementation of NMI test infrastructure interface
-# Simple wrapper to source the environment file and spawn the
-# corresponding perl script for a given stage of the test.
+use strict;
+use warnings;
+use File::Basename;
 
-ENV_FILE=setup_test_env
+my $dir = dirname($0);
+unshift @INC, $dir;
+require "TestGlue.pm";
+TestGlue::setup_test_environment();
 
-# include the environment info from the pre-script
-if [ ! -f $ENV_FILE ]; then
-    echo "$ENV_FILE does not exist!"
-    exit 1
-fi
-. $ENV_FILE
+my $BaseDir = $ENV{BASE_DIR} || die "BASE_DIR not in environment!\n";
+my $exit_status = 0;
 
-exec remote_post.pl $*
+# This is debugging output for the sake of the NWO infrastructure.
+# However, it might be useful to us some day so we can see what's
+# going on in case of failures...
+if( defined $ENV{_NMI_STEP_FAILED} ) { 
+    print "The value of _NMI_STEP_FAILED is: '$ENV{_NMI_STEP_FAILED}'\n";
+}
+else {
+    print "The _NMI_STEP_FAILED variable is not set\n";
+}
+
+
+######################################################################
+# kill test suite personal condor daemons
+######################################################################
+
+
+print "Seeing if personal condor needs killing\n";
+
+my $personal_condor_dir = File::Spec->catdir($BaseDir, "condor_tests", "TestingPersonalCondor");
+my $sentinel = File::Spec->catfile($personal_condor_dir, "local", "log", ".scheduler_address");
+if( -f $sentinel ) {
+    #  Came up and had a scheduler running. good
+    $ENV{CONDOR_CONFIG} = File::Spec->catfile($personal_condor_dir, "condor_config");
+    if( defined $ENV{_NMI_STEP_FAILED} ) { 
+        print "Not calling condor_off for $ENV{CONDOR_CONFIG}\n";
+    }
+    else {
+        print "Calling condor_off for $ENV{CONDOR_CONFIG}\n";
+        my $condor_off = File::Spec->catfile($BaseDir, "condor", "sbin", "condor_off");
+        system("$condor_off -master");
+
+        # give some time for condor to shutdown
+        sleep(30);
+        print "Done calling condor_off for $ENV{CONDOR_CONFIG}\n";
+    }
+}
+else {
+    # if there's no pid_file, there must be no personal condor running
+    # which we'd have to kill.  this would be caused by an empty
+    # tasklist.  so, make sure the tasklist is empty.  if so, we can
+    # move on with success.  if there are tasks but no pid_file,
+    # that's a weird fatal error and we should propagate that.
+    if( ! -f "tasklist.nmi" || -z "tasklist.nmi" ) {
+        # our tasklist is empty, good.
+        print "tasklist.nmi is empty and there's no condor_master_pid file.\n";
+        print "Nothing to cleanup, returning SUCCESS.\n";
+    }
+    else {
+        print "ERROR: tasklist.nmi contains data but condor_master_pid does not exist!\n";
+        $exit_status = 1;
+    }
+}
+    
+
+######################################################################
+# save and tar up test results
+######################################################################
+
+if( ! -f "tasklist.nmi" || -z "tasklist.nmi" ) {
+    # our tasklist is empty, so don't do any real work
+    print "No tasks in tasklist.nmi, nothing to do\n";
+    exit $exit_status;
+}
+
+print "cding to $BaseDir \n";
+chdir("$BaseDir") || die "Can't chdir($BaseDir): $!\n";
+
+#----------------------------------------
+# final tar and exit
+#----------------------------------------
+print "Tarring up all results\n";
+chdir("$BaseDir") || die "Can't chdir($BaseDir): $!\n";
+my $test_dir = File::Spec->catdir($BaseDir, "condor_tests");
+system("tar zcf results.tar.gz --exclude *.exe $test_dir local");
+
+exit $exit_status;
diff --git a/nmi_tools/glue/test/remote_pre b/nmi_tools/glue/test/remote_pre
--- a/nmi_tools/glue/test/remote_pre
+++ b/nmi_tools/glue/test/remote_pre
@@ -1,7 +1,7 @@
-#!/bin/sh
+#!/usr/bin/env perl
 ##**************************************************************
 ##
-## Copyright (C) 1990-2007, Condor Team, Computer Sciences Department,
+## Copyright (C) 1990-2011, Condor Team, Computer Sciences Department,
 ## University of Wisconsin-Madison, WI.
 ## 
 ## Licensed under the Apache License, Version 2.0 (the "License"); you
@@ -19,19 +19,221 @@
 ##**************************************************************
 
 
-# $Id: remote_pre,v 1.3 2007-11-08 22:53:46 nleroy Exp $
+######################################################################
+# script to set up for Condor testsuite run
+######################################################################
 
-# Condor implementation of NMI test infrastructure interface
-# Simple wrapper to source the environment file and spawn the
-# corresponding perl script for a given stage of the test.
+use strict;
+use warnings;
+use Cwd;
+use Env; 
+use File::Copy;
+use File::Basename;
 
-ENV_FILE=setup_test_env
+my $dir = dirname($0);
+unshift @INC, $dir;
+require "TestGlue.pm";
+TestGlue::setup_test_environment();
 
-# include the environment info from the pre-script
-if [ ! -f $ENV_FILE ]; then
-    echo "$ENV_FILE does not exist!"
-    exit 1
-fi
-. $ENV_FILE
+# Don't buffer output.
+$|=1;
 
-exec remote_pre.pl $*
+my $BaseDir = $ENV{BASE_DIR} || die "BASE_DIR not in environment!\n";
+my $logsize = "50000000"; # size for logs of personal Condor
+my $force_cygwin = 1; # force a switch to cygwin perl before running batch test.
+
+# Hard-coded filename, defined in test_platform_pre
+my $tarball_file = "CONDOR-TARBALL-NAME";
+
+if( -z "tasklist.nmi" ) {
+    # our tasklist is empty, so don't do any real work
+    print "No tasks in tasklist.nmi, nothing to do\n";
+    exit 0;
+}
+
+
+######################################################################
+# untar pre-built tarball
+######################################################################
+
+my $release_tarball;
+my $version;
+if( TestGlue::is_windows() ) {
+    # if there is a release_dir, assume that the condor binaries are there
+    # In that case, no unzipping is needed. just rename release_dir to condor
+    if ($ENV{COMPUTERNAME} =~ /^EXEC\-/) {
+		if (-d "release_dir" && ! -d "condor") {
+		   print "Renaming release_dir/ to condor/\n";
+		   rename("release_dir","condor");
+		   TestGlue::dir_listing("condor");
+	       
+		   my ($release_zipfile) = glob("condor-*.zip");
+		   if ($release_zipfile) {
+			  $version = substr($release_zipfile, 0, -4);
+			  print "VERSION string is $version from $release_zipfile\n";
+		   }
+		} 
+    }
+    
+    # if there is no release_dir, then look for a zip file
+    # containing the condor binaries and unzip it.
+    if (!(-d "condor")) {
+       print "Finding release zip file\n";
+       my ($release_zipfile) = glob("condor-*.zip");
+    
+       print "Release zip file is '$release_zipfile'\n";
+    
+       if( ! $release_zipfile ) {
+           die "Could not find a condor release zip file!\n";
+       }
+    
+       if ( ! mkdir("condor") ) {
+           die "Could not make the condor folder\n";
+       }
+
+		# We are explicitly calling unzip from C:\tools so that we do not use Cygwin's
+		# version of unzip.  When Cygwin unzips a tarball it removes the execute bits 
+		# and we have to restore them.  We want to avoid this so use non-Cygwin unzip
+		my $zip_exe_path = "C:\\tools\\unzip.exe";
+		if (!(-f $zip_exe_path)) {
+		   $zip_exe_path = "msconfig\\unzip.exe";
+		}
+		print "Unzipping $release_zipfile using $zip_exe_path\n";
+		system("$zip_exe_path $release_zipfile -d condor") && die "Can't unzip $release_zipfile: $!\n";
+		print "Unzipped $release_zipfile.\n";
+	    
+		(my $tmp_dir = basename($release_zipfile)) =~ s/\.zip$//;
+		print "\$tmp_dir = '$tmp_dir'\n";
+		TestGlue::dir_listing("condor");
+		my $tmp_dir_path = File::Spec->catdir("condor", $tmp_dir);
+		if( -d $tmp_dir_path ) {
+			print "$tmp_dir_path exists.  Trying to move...\n";
+			system("move $tmp_dir_path\\* condor\\");
+		}
+		TestGlue::dir_listing("condor");
+
+		$version = substr($release_zipfile, 0, -4);
+		print "VERSION string is $version from $release_zipfile\n";
+    }
+}
+else {
+    print "Finding release tarball\n";
+    open(TARBALL_FILE, '<', $tarball_file ) || die "Can't open $tarball_file: $!\n";
+    while(<TARBALL_FILE>) {
+        chomp;
+        $release_tarball = $_;
+    }
+    
+    print "Release tarball is '$release_tarball'\n";
+    
+    if( ! $release_tarball ) {
+        die "$tarball_file does not contain a filename!\n";
+    }
+    if( ! -f $release_tarball ) {
+        die "$release_tarball (from $tarball_file) does not exist!\n";
+    }
+    
+    print "Release tarball file exists:\n";
+    TestGlue::dir_listing($release_tarball);
+
+    print "Untarring $release_tarball ...\n";
+    system("tar -xzvf $release_tarball" ) && die "Can't untar $release_tarball: $!\n";
+    print "Untarred $release_tarball.\n";
+    
+    ($version) = $release_tarball =~ /^(.*)\.[^.]+\.[^.]+$/;
+    print "VERSION string is $version from $release_tarball\n";
+}
+
+######################################################################
+# setup the personal condor
+######################################################################
+
+print "Condor version: $version\n";
+
+print "SETTING UP PERSONAL CONDOR\n";
+
+# I'm not 100% certain wtf this actually does. 
+if( not TestGlue::is_windows() ) {
+    mkdir( "$BaseDir/local", 0777 ) || die "Can't mkdir $BaseDir/local: $!\n";
+    system("mv $BaseDir/$version $BaseDir/condor" );
+
+	if ( `uname` =~ "Linux" || `uname` =~ "Darwin" ) {
+		# On cross-platform testing, the binaries in condor_tests may need
+		# to find the extra system libraries we include. Let them find them
+		# when looking under $ORIGIN/../lib/condor.
+		system( "ln -s condor/lib lib" );
+	}
+    
+    # Remove leftovers from extracting built binaries.
+    print "Removing $version tar file and extraction\n";
+    unlink(<$version*>);
+}
+else {
+    # windows personal condor setup
+    mkdir( "local", 0777 ) || die "Can't mkdir $BaseDir/local: $!\n";
+    mkdir( "local/spool", 0777 ) || die "Can't mkdir $BaseDir/local/spool: $!\n";
+    mkdir( "local/execute", 0777 ) || die "Can't mkdir $BaseDir/local/execute: $!\n";
+    mkdir( "local/log", 0777 ) || die "Can't mkdir $BaseDir/local/log: $!\n";
+    
+    # Remove leftovers from extracting built binaries.
+    print "Removing *.zip files\n";
+    unlink(<*.zip>);
+
+    my $Win32BaseDir = $ENV{WIN32_BASE_DIR} || die "WIN32_BASE_DIR not in environment!\n";
+   
+    if ($^O =~ /MSWin32/) {
+        my $which_master = `\@for \%I in (condor_master.exe) do \@echo(%~\$PATH:I`;
+        print "which condor_master is $which_master\n";
+        if ($which_master =~ /^[a-z]:\\condor\\bin\\/i) {
+            print "removing base condor from the path and trying again\n";
+            my $tpath = $ENV{PATH};
+            $tpath =~ s/^[a-z]:\\condor\\bin[\\]?;//ig;
+            $ENV{PATH} = $tpath;
+            $which_master = `\@for \%I in (condor_master.exe) do \@echo(%~\$PATH:I`;
+            print "which condor_master is now $which_master\n";
+        }
+    } else {
+    	TestGlue::which("condor_master.exe");
+    }
+    
+	# must use cygwin perl on Windows for batch_test.pl in old batlab
+	print "Currently running $^O Perl\n";
+	if (!($^O =~ /cygwin/)) {
+		if ( ! $force_cygwin && ($ENV{COMPUTERNAME} =~ /^EXEC\-/)) {
+			print "attempting to run tests using current perl\n";
+			#$ENV{PATH} = "$Win32BaseDir\\msconfig;$ENV{PATH}";
+			print "PATH=$ENV{PATH}\n";
+		} else {
+			print "adding cygwin to the front of the path\n";
+			$ENV{PATH} = "c:\\cygwin\\bin;$ENV{PATH}";
+			print "PATH=$ENV{PATH}\n";
+
+			#$perl_exe = "c:\\cygwin\\bin\\perl";
+			#print "Invoking cygwin perl by explicit path ($perl_exe)\n";
+			my $perlver = `perl -version`;
+			print "----------------------------------\n";
+			print $perlver;
+			print "----------------------------------\n";
+			if (!($perlver =~ /cygwin/i)) {
+				die "cygwin perl not found!\n";
+			}
+		}
+	}
+}
+
+
+# move into the condor_tests directory first
+my $test_dir = File::Spec->catdir($BaseDir, "condor_tests");
+chdir($test_dir) || die "Can't chdir($test_dir for personal condor setup): $!\n";
+
+# -p means just set up the personal condor for the test run
+my $batch_test = File::Spec->catfile($test_dir, "batch_test.pl");
+my $command_line = "$batch_test --debug -p";
+print "About to run '$command_line'\n";
+system("perl $command_line");
+
+if( $? != 0 ) {
+    print "--- the last 50 lines of TestingPersonalCondor/local/log/MasterLog\n";
+    system("tail -50 $test_dir/TestingPersonalCondor/local/log/MasterLog");
+    exit 2;
+}
