Add support for Mac OS X to Condor

diff --git a/src/condor_imake b/src/condor_imake
--- a/src/condor_imake
+++ b/src/condor_imake
@@ -8,57 +8,6 @@ fi
 
 
 ##################################################
-# Find imake.  
-# If it doesn't yet exist, build it.
-##################################################
-
-IMAKE=imake
-if [ X$USE_OLD_IMAKE = X ] ; then
-if [ -d ../imake ] ; then
-    IMAKEROOT="../imake"
-elif [ -d ../../imake ] ; then
-    IMAKEROOT="../../imake"
-elif [ -d ../../../imake ] ; then
-    IMAKEROOT="../../../imake"
-else
-	echo "Can't find the root directory for imake!"
-	echo "You need a copy of imake build Condor."
-	echo "Please make sure your version of the Condor source"
-	echo "contains a directory called \"imake\" that is at the"
-	echo "top-level of your source tree (next to \"src\", \"config\")"
-	exit 1
-fi
-
-IMAKE="$IMAKEROOT/imake"
-if [ ! -x $IMAKE ] ; then
-    echo "Attemping to build imake from source"
-    pwd=`pwd`
-    cd $IMAKEROOT
-    make
-    cd $pwd
-fi
-if [ ! -x $IMAKE ] ; then
-    # if it's not here yet, fatal error
-    echo "Failed to build imake!"
-p   exit 1
-fi
-
-# Now, find an appropriate cpp to use
-IMAKECPP="$IMAKEROOT/imake_cpp"
-if [ ! -x $IMAKECPP ] ; then
-    if [ -f $IMAKECPP ] ; then
-        rm -f $IMAKECPP
-    fi	 
-    echo '#!/bin/sh' > $IMAKECPP
-    echo 'gcc -E -w $*' >> $IMAKECPP
-    chmod 755 $IMAKECPP
-fi
-export IMAKECPP
-
-# end of USE_OLD_IMAKE
-fi
-
-##################################################
 # Figure out the flags for imake to build Makefile
 ##################################################
 
@@ -111,6 +60,8 @@ fi
 LIBGCC=`gcc -print-libgcc-file-name`
 EgcsLib="-DLIB_GCC=$LIBGCC"
 
+Imakecppflags="gcc -E -w \$*"
+
 if [ $os = "HP-UX" -a "$osrelease" = "B.10.20" ] ; then
 	Opsys="-DIS_HPUX10"
 
@@ -118,11 +69,11 @@ elif [ $os = "HP-UX" -a "$osversion" = "B.11.00" ] ; then
 	Opsys="-DIS_HPUX11"
 
 elif [ $os = "OSF1" ] ; then
-	if [ $osrelease = "V4.0" ] ; then
-		Opsys="-DIS_DUX4"
-	elif [ $osrelease = "V5.0" -o $osrelease = "V5.1" ] ; then
-		Opsys="-DIS_DUX5"
-	fi
+        if [ $osrelease = "V4.0" ] ; then
+                Opsys="-DIS_DUX4"
+        elif [ $osrelease = "V5.0" -o $osrelease = "V5.1" ] ; then
+                Opsys="-DIS_DUX5"
+        fi
 
 elif [ $os = "Linux" ]; then
 	Opsys="-DIS_LINUX"
@@ -187,9 +138,65 @@ elif [ $os = "AIX" ] ; then
 
 	# add detection to this when ia64 is needed
 	ArchFlag="-DIS_PPC"
+
+elif [ $os = "Darwin" ] ; then
+	Opsys="-DIS_BSD -DIS_DARWIN"
+	Imakecppflags="gcc -E -w  -no-cpp-precomp \$*"
 else
-	echo "Unknown O/S: OS=\"$os\" Version=\"$osversion\""
+        echo "Unknown O/S: OS=\"$os\" Version=\"$osversion\""
+        exit 1
+
+fi
+
+##################################################
+# Find imake.  
+# If it doesn't yet exist, build it.
+##################################################
+
+IMAKE=imake
+if [ X$USE_OLD_IMAKE = X ] ; then
+if [ -d ../imake ] ; then
+    IMAKEROOT="../imake"
+elif [ -d ../../imake ] ; then
+    IMAKEROOT="../../imake"
+elif [ -d ../../../imake ] ; then
+    IMAKEROOT="../../../imake"
+else
+	echo "Can't find the root directory for imake!"
+	echo "You need a copy of imake build Condor."
+	echo "Please make sure your version of the Condor source"
+	echo "contains a directory called \"imake\" that is at the"
+	echo "top-level of your source tree (next to \"src\", \"config\")"
 	exit 1
+fi
+
+IMAKE="$IMAKEROOT/imake"
+if [ ! -x $IMAKE ] ; then
+    echo "Attemping to build imake from source"
+    pwd=`pwd`
+    cd $IMAKEROOT
+    make
+    cd $pwd
+fi
+if [ ! -x $IMAKE ] ; then
+    # if it's not here yet, fatal error
+    echo "Failed to build imake!"
+p   exit 1
+fi
+
+# Now, find an appropriate cpp to use
+IMAKECPP="$IMAKEROOT/imake_cpp"
+if [ ! -x $IMAKECPP ] ; then
+    if [ -f $IMAKECPP ] ; then
+        rm -f $IMAKECPP
+    fi	 
+    echo '#!/bin/sh' > $IMAKECPP
+    echo $Imakecppflags >> $IMAKECPP
+    chmod 755 $IMAKECPP
+fi
+export IMAKECPP
+
+# end of USE_OLD_IMAKE
 fi
 
 ##################################################
@@ -198,3 +205,4 @@ fi
 
 echo $IMAKE -s Makefile $ArchFlag $Opsys $Other $Other2 $EgcsLib $KerbFlags -I../config -I../../config $*
 $IMAKE -s Makefile $ArchFlag $Opsys $Other $Other2 $EgcsLib $KerbFlags -I../config -I../../config $*
+
