merged V6_4-branch (as tagged at V6_4-branch-2) into V6_5-branch.

diff --git a/src/condor_imake b/src/condor_imake
--- a/src/condor_imake
+++ b/src/condor_imake
@@ -6,6 +6,58 @@ if [ -d CVS ]; then
 	exit 1
 fi
 
+
+##################################################
+# Find imake.  
+# If it doesn't yet exist, build it.
+##################################################
+
+if [ -d ../imake ] ; then
+    IMAKEROOT="../imake"
+elif [ -d ../../imake ] ; then
+    IMAKEROOT="../../imake"
+elif [ -d ../../../imake ] ; then
+    IMAKEROOT="../../../imake"
+else
+	echo "Can't find the root directory for imake!"
+	echo "You need a copy of imake build Condor."
+	echo "Please make sure your version of the Condor source"
+	echo "contains a directory called \"imake\" that is at the"
+	echo "top-level of your source tree (next to \"src\", \"config\")"
+	exit 1
+fi
+
+IMAKE="$IMAKEROOT/imake"
+if [ ! -x $IMAKE ] ; then
+    echo "Attemping to build imake from source"
+    pwd=`pwd`
+    cd $IMAKEROOT
+    make
+    cd $pwd
+fi
+if [ ! -x $IMAKE ] ; then
+    # if it's not here yet, fatal error
+    echo "Failed to build imake!"
+p   exit 1
+fi
+
+# Now, find an appropriate cpp to use
+IMAKECPP="$IMAKEROOT/imake_cpp"
+if [ ! -x $IMAKECPP ] ; then
+    if [ -f $IMAKECPP ] ; then
+        rm -f $IMAKECPP
+    fi	 
+    echo '#!/bin/sh' > $IMAKECPP
+    echo 'gcc -E -w $*' >> $IMAKECPP
+    chmod 755 $IMAKECPP
+fi
+export IMAKECPP
+
+
+##################################################
+# Figure out the flags for imake to build Makefile
+##################################################
+
 arch=`uname -m`
 osversion=`uname -r`
 # Make sure if we get back something that begins with "IRIX" that we
@@ -32,6 +84,16 @@ elif [ -f /usr/kerberos/lib/libkrb5.a ] ; then
 	KerbPath="-DKERBEROS_PATH=/usr/kerberos"
 	HasKerb="-DHAS_KERBEROS=YES"
 	if [ -f /usr/kerberos/lib/libk5crypto.a ] ; then
+		KerbK5="-DKERBEROS_K5=YES"
+	else
+		KerbK5="-DKERBEROS_K5=NO"
+	fi
+
+	KerbFlags="$KerbPath $HasKerb $KerbK5"
+elif [ -f /usr/local/lib/libkrb5.a ] ; then
+	KerbPath="-DKERBEROS_PATH=/usr/local"
+	HasKerb="-DHAS_KERBEROS=YES"
+	if [ -f /usr/local/lib/libk5crypto.a ] ; then
 		KerbK5="-DKERBEROS_K5=YES"
 	else
 		KerbK5="-DKERBEROS_K5=NO"
@@ -85,6 +147,8 @@ elif [ $os = "SunOS" ]; then
 		Opsys="-DIS_SOLARIS27"
 	elif [ $osversion = "5.8" ] ; then
 		Opsys="-DIS_SOLARIS28"
+	elif [ $osversion = "5.9" ] ; then
+		Opsys="-DIS_SOLARIS29"
 	fi
 
 elif [ $os = "IRIX" ] ; then
@@ -95,7 +159,9 @@ elif [ $os = "IRIX" ] ; then
 	fi
 fi
 
-echo imake -s Makefile $ArchFlag $Opsys $Other $Other2 $EgcsLib $KerbFlags -I../config -I../../config $*
+##################################################
+# Finally, call imake with all the flags
+##################################################
 
-imake -s Makefile $ArchFlag $Opsys $Other $Other2 $EgcsLib $KerbFlags -I../config -I../../config $*
+$IMAKE -s Makefile $ArchFlag $Opsys $Other $Other2 $EgcsLib $KerbFlags -I../config -I../../config $*
 
